# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli
# [migrations_directory]のdirにはローカルのパスは含まないこと

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "migrations"
